### ISSUE TITLE
Improvement: Allow multiple topics of interest (for mentees)

### ISSUE THREAD

**Issue by jannesiera** [Kavignon/Mentorship-pairing-script#14]
I believe that currently mentors can specify multiple 'fields of expertise' but that mentees can only select one topic that they want to learn. We will open this up so that mentees can select multiple topics they might be interested in. The matcher should be reviewed if it can deal with this scenario and changed if necessary.

**Comment by kaeedo** [comment]
Hello. I've taken a look at the matcher, and it seems to be able to handle multiple topics for mentees without a problem. The only thing that would need to be updated would be the CSV header from `What topic do you want to learn?` to `What topics do you want to learn?`.

**Comment by giorgiovilardo** [comment]
Seems just like @kaeedo said: one point to notice is that the generated email has just one topic even if mentor+mentee agree on more than one topic.

**Comment by giorgiovilardo** [comment]
https://github.com/Kavignon/FSharp-Mentorship-Automatic-Planner/pull/16 this creates an email with an expanded list of matched interests. Done to just spark more discussion and to practice a bit with the codebase :)

**Comment by Kavignon** [comment]
Let me check your PR @giorgiovilardo 
Thanks for the contribution! :)
