### ISSUE TITLE
Documentation: We need some

### ISSUE THREAD

**Issue by jannesiera** [Kavignon/Mentorship-pairing-script#15]
Creating some documentation in the form of a README might be interesting at some point.

**Comment by ghost** [comment]
I will take care of this one. Is there anything you would like to see besides usage and build instructions and a description of the CSV format?

**Comment by Kavignon** [comment]
I can help you with this, but this sounds like a pretty good start! Thanks!

**Comment by ghost** [comment]
OK, I'll be working on it this weekend then. I'll ask you if I have any question. 🙂

**Comment by Kavignon** [comment]
Hey @sharptom I just checked an old PR of mine. I think you can add a bit more stuff but I was working on documentation in the readme in the past: https://github.com/Kavignon/FSharp-Mentorship-Automatic-Planner/pull/10/commits
